name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: install dependencies
      run: npm ci

    - name: build
      run: npm run build

    - name: Upload Files
      id: upload
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{secrets.SERVER_URL}}
        port: 22
        username: ${{secrets.SERVER_USERNAME}}
        password: ${{secrets.SERVER_PASSWORD}}
        local_path: './dist'
        remote_path: './astro'
        delete_remote_files: true
        sftp_only: true